# Generated by Django 2.2.2 on 2019-06-28 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'Pessoas'},
        ),
    ]
